export default [
    {
      bg: '#A8DDE9',
      color: '#3F5B98',
      category: '1st Floor GW 01',
      subCategories: ['Skincare', 'Personal care', 'Health', 'Eye care'],
    },
    {
      bg: '#086E4B',
      color: '#FCBE4A',
      category: '2nd Floor GW 02',
      subCategories: [
        'Fruits & Vegetables',
        'Frozen Food',
        'Bakery',
        'Snacks & Desserts',
        'Beverages',
        'Alcoholic beverages',
        'Noodles & Pasta',
        'Rice & Cooking oil',
      ],
    },
    {
      bg: '#FECBCA',
      color: '#FD5963',
      category: '3rd Floor GW 03',
      subCategories: ['Skincare', 'Makeup', 'Nail care', 'Perfume'],
    },
    {
      bg: '#193B8C',
      color: '#FECBCD',
      category: '4th Floor GW 04',
      subCategories: [
        'Toys',
        'Trolleys',
        'LEGO®',
        'Electronics',
        'Puzzles',
        'Costumes',
        'Food',
        'Hygiene & Care',
        "Child's room",
        'Feeding accessories',
      ],
    },
    {
      bg: '#FDBD50',
      color: '#F5F5EB',
      category: '5th Floor GW 05',
      subCategories: [
        'Air purifiers',
        'Stoves, hoods & ovens',
        'Refrigerators',
        'Coffee & Tea',
        'Air conditioning',
        'Grilling',
        'Vacuum cleaners',
      ],
    },
  ];